/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Felipe' at '08/08/16 19:08' with Gradle 2.9
 *
 * @author Felipe, @date 08/08/16 19:08
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
